export const DEFAULT_TEXT_COLORS = [
  { name: "Blanc", hex: "#FFFFFF" },
  { name: "Noir", hex: "#000000" },
];

export const DEFAULT_BG_COLORS = [
  { name: "Bleu nuit", hex: "#00005b" },
  { name: "Bleu foncé", hex: "#003a80" },
  { name: "Bleu outremer", hex: "#0064b0" },
  { name: "Bleu clair", hex: "#51afdf" },
  { name: "Bleu canard", hex: "#003c5f" },
  { name: "Pervenche", hex: "#82c8e6" },
  { name: "Turquoise", hex: "#00a88f" },
  { name: "Vert foncé", hex: "#00814f" },
  { name: "Vert clair", hex: "#7ab829" },
  { name: "Émeraude", hex: "#198250" },
  { name: "Sapin", hex: "#00643c" },
  { name: "Bambou", hex: "#96be00" },
  { name: "Acacia", hex: "#d2d200" },
  { name: "Jaune vif", hex: "#ffcd00" },
  { name: "Jaune ocre", hex: "#dfb039" },
  { name: "Mandarine", hex: "#ff7d00" },
  { name: "Orange", hex: "#ed6e00" },
  { name: "Rouge coquelicot", hex: "#e3051b" },
  { name: "Rouge framboise", hex: "#d33c56" },
  { name: "Saumon", hex: "#ff645a" },
  { name: "Rose", hex: "#fd8db6" },
  { name: "Magenta", hex: "#cc1971" },
  { name: "Fuchsia", hex: "#dc5ab4" },
  { name: "Lilas", hex: "#c085b6" },
  { name: "Violet", hex: "#6e32c9" },
  { name: "Marron", hex: "#8d5e2a" },
  { name: "Olive clair", hex: "#a4b72b" },
  { name: "Olive foncé", hex: "#6f8021" },
  { name: "Perle", hex: "#f0dcd2" },
  { name: "Élysée", hex: "#6e645a" },
  { name: "Noir", hex: "#000000" },
];
